
spring: 
  application: 
    name: Flight-service
  data: 
    mongodb: 
      database: flightsdb
      host: localhost
      port: 27017
server: 
  port: 3333
eureka:  
  client:
    healthcheck:
      enabled: true    
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
zuul:
  routes:
    flights: /Flight-service/**